on:
  pull_request:
    types: [opened, synchronize]

jobs:
  dockerfile-linter:
    runs-on: self-hosted
    name: Dockerfile Linter
    steps:
    - uses: actions/checkout@v2
    - name: Run Dockerfile Linter on Back-end
      run: docker run --rm -i hadolint/hadolint < ./docker/todo-app/back-end/Dockerfile
    - name: Run Dockerfile Linter on Front-end
      run: docker run --rm -i hadolint/hadolint < ./docker/todo-app/front-end/Dockerfile
    - name: Run Dockerfile Linter on Tests
      run: docker run --rm -i hadolint/hadolint < ./docker/todo-app/tests/Dockerfile

  evaluator:
    runs-on: self-hosted
    name: Evaluator
    needs: [dockerfile-linter]
    steps:

      - name: Fetch project repository
        uses: actions/checkout@v2

      - name: Fetch Blocked Files Checkout action
        uses: actions/checkout@v2
        with:
          repository: betrybe/blocked-files-checkout-action
          ref: v2
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/blocked-files-checkout

      - name: Fetch Docker Jest evaluator
        uses: actions/checkout@v2
        with:
          repository: betrybe/docker-jest-evaluator-action
          ref: v1
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/docker-jest-evaluator

      - name: Fetch Store evaluation
        uses: actions/checkout@v2
        with:
          repository: betrybe/store-evaluation-action
          ref: v4.2
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/store-evaluation

      - name: Setup NodeJS
        uses: actions/setup-node@v1.4.4
        with:
          node-version: '14'

      - name: Restore protected files
        uses: ./.github/actions/blocked-files-checkout
        with:
          restore_branch: 'master'

      - name: Run Docker Jest evaluation
        id: jest_eval
        uses: ./.github/actions/docker-jest-evaluator
        with:
          pr_author_username: ${{ github.event.pull_request.user.login }}

      - name: Run Store evaluation
        uses: ./.github/actions/store-evaluation
        with:
          evaluation-data: ${{ steps.jest_eval.outputs.result }}
          environment: production
          pr-number: ${{ github.event.pull_request.number }}
